name: Check raw color classes

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'src/**'

jobs:
  check-raw-colors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run raw colors scanner
        run: npm run check:raw-colors
